### ISSUE TITLE
Variable workspacfunc on Matlab2015a Ubuntu

### ISSUE THREAD

**Issue by gatufella** [bayesnet/bnt#47]
When running the mixtureBNT.m tutorial an Exception appears:

![error](https://cloud.githubusercontent.com/assets/5598958/17813995/a19c6624-6625-11e6-8502-580a4835261b.png)

This window blocks the usage of the editor so it is very annoying to close it every time the script is run. It also shows when trying to view the variable contents in the workspace.
```
>> mixtureBNT

ans =

   570    31


ans =

   120    31

EM iteration 1, ll = -20253.8215
EM iteration 2, ll = 6959.8467
EM iteration 3, ll = 6959.8470
EM iteration 4, ll = 6959.8479
EM iteration 5, ll = 6959.8514
EM iteration 6, ll = 6959.8654
EM iteration 7, ll = 6959.9158
EM iteration 8, ll = 6960.0552
EM iteration 9, ll = 6960.2468
EM iteration 10, ll = 6960.2868

Current plot held
Current plot held
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: [D cannot be cast to [Z
	at com.mathworks.mlwidgets.array.ValuePanel$ROML.matlabEvent(ValuePanel.java:251)
	at com.mathworks.jmi.MatlabMCR$AWTReplyEvent.run(MatlabMCR.java:1636)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$200(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.awt.Dialog.show(Unknown Source)
	at com.mathworks.mwswing.MJDialog.show(MJDialog.java:311)
	at java.awt.Component.show(Unknown Source)
	at java.awt.Component.setVisible(Unknown Source)
	at java.awt.Window.setVisible(Unknown Source)
	at java.awt.Dialog.setVisible(Unknown Source)
	at com.mathworks.mwswing.MJOptionPane.showOptionDialog(MJOptionPane.java:539)
	at com.mathworks.mwswing.MJOptionPane.showMessageDialog(MJOptionPane.java:435)
	at com.mathworks.mwswing.MJOptionPane.showMessageDialog(MJOptionPane.java:425)
	at com.mathworks.mlwidgets.array.ArrayDialog$1.run(ArrayDialog.java:49)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$200(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by Ionhihir** [comment]
Dear gatufella. 

I'm sorry you experience difficulties. 

Since matlab2014b, draw_graph doesn't work anymore. 

You could even 
- downgrade to Matlab 2013b; 
- run the test script while commenting all % draw_graph commands; 
- download the newest version of graphviz for matlab. 

I will publish a new version later without this overcome (mid september i hope). 
A student of mine have correct it. 

Best regards. 

Olivier FRANÇOIS 
01 81 66 87 23 
COSYS / GRETTIA

**Comment by gatufella** [comment]
Dear Olivier,

Many thanks for your reply. Look forward to the update.

Cheers,

Mariela De Lucas
